service: gasket-js
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  memorySize: 128
  profile: serverless-admin
  environment:
    API_KEY: 'AUHaWvNJ99slebQ49haZ'

functions:
  api:
    handler: src/gasket.handler
    events:
      - http:
          path: /gasket
          method: GET
          cors: true
          private: true

plugins:
  - serverless-esbuild
